services:

  client:

    build: ./client

    ports:
      - "8080:8080"
    
    volumes:
      - ./client:/app
      - /app/node_modules
    
    environment:
      - CHOKIDAR_USEPOLLING=true
      
    tty: true
      
    networks:
      - backend

    depends_on:
      - server

  server:

    build: ./server

    ports:
      - "3000:3000"

    volumes:
      - ./server:/app
      - /app/node_modules
    
    env_file:
      - .env
    
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_SERVER=db
      - TZ=${TZ}
      
    tty: true
      
    networks:
      - backend

    depends_on:
      - db
  
  db:

    image: mysql:8.0

    env_file:
      - .env

    # command: >
    #   bash -c '
    #     echo "Excecute db build command."'

    # bash -c '
    #   mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER IF NOT EXISTS \'$MYSQL_USER\'@\'%\' IDENTIFIED BY \'$MYSQL_PASSWORD\'";
    #   mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO \'$MYSQL_USER\'@\'%\'";
    #   mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES";
    #   exec mysqld'

    ports:
      - "3306:3306"

    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
      
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
